const menusData = [
  {
    title: "dashboard",
    allowedRoles: [
      "admin",
      "nurse",
      "cashier",
      "pharmacy",
      "pharmacy_store",
      "labratory",
      "imaging",
      "labratory_head",
      "imaging_head",
      "opd",
      "store",
      "reception",
    ],
    route: "dashboard",
  },
  {
    title: "patients",
    allowedRoles: ["nurse", "opd", "reception"],
    links: [
      {
        title: "patients",
        route: "patinets",
        icon: "patinets",
        allowedRoles: ["reception"],
      },
      {
        title: "nurse",
        route: "nurse",
        icon: "nurse",
        allowedRoles: ["nurse", "opd"],
      },
      {
        title: "opd",
        route: "opd",
        icon: "opd",
        allowedRoles: ["opd"],
      },
      {
        title: "appointments",
        route: "appointments",
        icon: "appointments",
        allowedRoles: ["reception", "opd", "nurse"],
      },
    ],
  },
  {
    title: "inventory",
    allowedRoles: [
      "admin",
      "nurse",
      "cashier",
      "pharmacy",
      "pharmacy_store",
      "labratory",
      "imaging",
      "labratory_head",
      "imaging_head",
      "opd",
      "store",
      "reception",
    ],
    links: [
      {
        title: "pharmacy",
        route: "pharmacy",
        icon: "pharmacy",
        allowedRoles: ["pharmacy", "pharmacy_store"],
      },
      {
        title: "pharmacy_store",
        route: "pharmacy_store",
        icon: "pharmacy_store",
        allowedRoles: ["pharmacy_store"],
      },
      {
        title: "measurment_unit",
        route: "measurmentUnitPharamcy",
        icon: "measurmentUnitPharamcy",
        allowedRoles: ["pharmacy_store"],
      },
      {
        title: "dispensary",
        route: "dispensary",
        icon: "dispensary",
        allowedRoles: ["pharmacy_store"],
      },
      {
        title: "prescription",
        route: "prescription",
        icon: "prescription",
        allowedRoles: ["opd", "pharmacy"],
      },
      {
        title: "measurment_unit",
        route: "measurmentUnit",
        icon: "measurmentUnit",
        allowedRoles: ["store"],
      },
      {
        title: "store",
        route: "store",
        icon: "store",
        allowedRoles: ["store"],
      },
      {
        title: "issue",
        route: "issue",
        icon: "issue",
        allowedRoles: [
          "admin",
          "nurse",
          "cashier",
          "pharmacy",
          "pharmacy_store",
          "labratory",
          "imaging",
          "labratory_head",
          "imaging_head",
          "opd",
          "store",
          "reception",
        ],
      },
    ],
  },
  {
    title: "medical_services",
    allowedRoles: ["labratory", "imaging", "labratory_head", "imaging_head"],
    links: [
      {
        title: "labratory_test",
        route: "labratoryTest",
        icon: "labratoryTest",
        allowedRoles: ["labratory", "labratory_head"],
      },
      {
        title: "labratory_result",
        route: "labratoryResult",
        icon: "labratoryResult",
        allowedRoles: ["labratory", "labratory_head"],
      },
      {
        title: "imaging_test",
        route: "imagingTest",
        icon: "imagingTest",
        allowedRoles: ["imaging", "imaging_head"],
      },
      {
        title: "imaging_result",
        route: "imagingResult",
        icon: "imagingResult",
        allowedRoles: ["imaging", "imaging_head"],
      },
    ],
  },
  {
    title: "organization",
    allowedRoles: ["admin"],
    links: [
      {
        title: "staff",
        route: "staff",
        icon: "staff",
        allowedRoles: ["admin"],
      },
      {
        title: "departments",
        route: "departments",
        icon: "departments",
        allowedRoles: ["admin"],
      },
      {
        title: "insurance",
        route: "insurance",
        icon: "insurance",
        allowedRoles: ["admin"],
      },
    ],
  },
  {
    title: "finance",
    allowedRoles: ["cashier"],
    links: [
      // {
      //   title: "transactions",
      //   route: "transactions",
      //   icon: "transactions",
      //   allowedRoles: ["cashier"],
      // },
      // {
      //   title: "financial_reports",
      //   route: "financialReports",
      //   icon: "financialReports",
      //   allowedRoles: ["cashier"],
      // },
      {
        title: "payment",
        route: "payment",
        icon: "payment",
        allowedRoles: ["cashier"],
      },
    ],
  },
  {
    title: "setting",
    allowedRoles: [
      "admin",
      "nurse",
      "cashier",
      "pharmacy",
      "pharmacy_store",
      "labratory",
      "imaging",
      "labratory_head",
      "imaging_head",
      "opd",
      "store",
      "reception",
    ],
    links: [
      {
        title: "hospital_setting",
        allowedRoles: ["admin"],
        route: "hospitalSetting",
        icon: "hospitalSetting",
      },
      {
        title: "role_and_permission",
        allowedRoles: ["admin"],
        route: "rolePermission",
        icon: "rolePermission",
      },
      {
        title: "change_password",
        allowedRoles: ["admin"],
        route: "changePassword",
        icon: "changePassword",
      },
    ],
  },
  {
    title: "others",
    allowedRoles: [
      "admin",
      "nurse",
      "cashier",
      "pharmacy",
      "pharmacy_store",
      "labratory",
      "imaging",
      "labratory_head",
      "imaging_head",
      "opd",
      "store",
      "reception",
    ],
    links: [
      {
        title: "work_permission",
        allowedRoles: [
          "admin",
          "nurse",
          "cashier",
          "pharmacy",
          "pharmacy_store",
          "labratory",
          "imaging",
          "labratory_head",
          "imaging_head",
          "opd",
          "store",
          "reception",
        ],
        route: "workPermission",
        icon: "workPermission",
      },
      {
        title: "annual_plan",
        allowedRoles: [
          "admin",
          "nurse",
          "cashier",
          "pharmacy",
          "pharmacy_store",
          "labratory",
          "imaging",
          "labratory_head",
          "imaging_head",
          "opd",
          "store",
          "reception",
        ],
        route: "annualPlan",
        icon: "annualPlan",
      },
      {
        title: "room",
        allowedRoles: ["admin"],
        route: "room",
        icon: "room",
      },
    ],
  },

  {
    title: "chat",
    allowedRoles: [
      "admin",
      "nurse",
      "cashier",
      "pharmacy",
      "pharmacy_store",
      "labratory",
      "imaging",
      "labratory_head",
      "imaging_head",
      "opd",
      "store",
      "reception",
    ],
    route: "chat",
    icon: "chat",
  },
];
export { menusData };
