const menusData = [
  {
    title: "Dashboard",
    allowedRoles: [
      "admin",
      "nurse",
      "cashier",
      "pharmacy",
      "labratory",
      "imaging",
      "labratory_head",
      "imaging_head",
      "opd",
      "store",
      "reception",
      "hrm",
    ],
    route: "dashboard",
  },
  {
    title: "Patients",
    allowedRoles: ["nurse", "opd", "reception"],
    links: [
      {
        title: "Patients",
        route: "patinets",
        icon: "patinets",
        allowedRoles: ["reception"],
      },
      {
        title: "Nurse",
        route: "nurse",
        icon: "nurse",
        allowedRoles: ["nurse", "opd"],
      },
      {
        title: "OPD",
        route: "opd",
        icon: "opd",
        allowedRoles: ["opd"],
      },
      {
        title: "Appointments",
        route: "appointments",
        icon: "appointments",
        allowedRoles: ["reception", "opd", "nurse"],
      },
    ],
  },
  {
    title: "Inventory",
    allowedRoles: [
      "admin",
      "nurse",
      "cashier",
      "pharmacy",
      "labratory",
      "imaging",
      "labratory_head",
      "imaging_head",
      "opd",
      "store",
      "reception",
    ],
    links: [
      {
        title: "Pharmacy",
        route: "pharmacy",
        icon: "pharmacy",
        allowedRoles: ["pharmacy"],
      },
      {
        title: "Prescription",
        route: "prescription",
        icon: "prescription",
        allowedRoles: ["opd", "pharmacy"],
      },
      {
        title: "Measurment Unit",
        route: "measurmentUnit",
        icon: "measurmentUnit",
        allowedRoles: ["admin"],
      },
      {
        title: "Store",
        route: "store",
        icon: "store",
        allowedRoles: ["store"],
      },
      {
        title: "Issue",
        route: "issue",
        icon: "issue",
        allowedRoles: [
          "admin",
          "nurse",
          "cashier",
          "pharmacy",
          "labratory",
          "imaging",
          "labratory_head",
          "imaging_head",
          "opd",
          "store",
          "reception",
        ],
      },
    ],
  },
  {
    title: "Medical Services",
    allowedRoles: ["labratory", "imaging", "labratory_head", "imaging_head"],
    links: [
      {
        title: "Labratory Test",
        route: "labratoryTest",
        icon: "labratoryTest",
        allowedRoles: ["labratory", "labratory_head"],
      },
      {
        title: "Labratory Result",
        route: "labratoryResult",
        icon: "labratoryResult",
        allowedRoles: ["labratory", "labratory_head"],
      },
      {
        title: "Imaging Test",
        route: "imagingTest",
        icon: "imagingTest",
        allowedRoles: ["imaging", "imaging_head"],
      },
      {
        title: "Imaging Result",
        route: "imagingResult",
        icon: "imagingResult",
        allowedRoles: ["imaging", "imaging_head"],
      },
    ],
  },
  {
    title: "Organization",
    allowedRoles: ["admin", "hrm"],
    links: [
      {
        title: "Staff",
        route: "staff",
        icon: "staff",
        allowedRoles: ["hrm"],
      },
      {
        title: "Departments",
        route: "departments",
        icon: "departments",
        allowedRoles: ["admin"],
      },
      {
        title: "Insurance",
        route: "insurance",
        icon: "insurance",
        allowedRoles: ["admin", "hrm"],
      },
    ],
  },
  {
    title: "Finance",
    allowedRoles: ["cashier"],
    links: [
      {
        title: "Dashboard",
        route: "financedashboard",
        icon: "dashboard",
        allowedRoles: ["cashier"],
      },
      {
        title: "Transactions",
        route: "transactions",
        icon: "transactions",
        allowedRoles: ["cashier"],
      },
      {
        title: "Financial Reports",
        route: "financialReports",
        icon: "financialReports",
        allowedRoles: ["cashier"],
      },
      {
        title: "Payment",
        route: "payment",
        icon: "payment",
        allowedRoles: ["cashier"],
      },
    ],
  },
  {
    title: "Setting",
    allowedRoles: [
      "admin",
      "nurse",
      "cashier",
      "pharmacy",
      "labratory",
      "imaging",
      "labratory_head",
      "imaging_head",
      "opd",
      "store",
      "reception",
      "hrm",
    ],
    links: [
      {
        title: "Hospital Setting",
        allowedRoles: ["admin"],
        route: "hospitalSetting",
        icon: "hospitalSetting",
      },
      {
        title: "Role and Permission",
        allowedRoles: ["admin"],
        route: "rolePermission",
        icon: "rolePermission",
      },
      {
        title: "Change Password",
        allowedRoles: ["admin"],
        route: "changePassword",
        icon: "changePassword",
      },
      {
        title: "Annual Report",
        allowedRoles: [
          "admin",
          "nurse",
          "cashier",
          "pharmacy",
          "labratory",
          "imaging",
          "labratory_head",
          "imaging_head",
          "opd",
          "store",
          "reception",
          "hrm",
        ],
        route: "annualReport",
        icon: "annualReport",
      },
    ],
  },
  {
    title: "Others",
    allowedRoles: [
      "admin",
      "nurse",
      "cashier",
      "pharmacy",
      "labratory",
      "imaging",
      "labratory_head",
      "imaging_head",
      "opd",
      "store",
      "reception",
      "hrm",
    ],
    links: [
      {
        title: "Work Permission",
        allowedRoles: [
          "admin",
          "nurse",
          "cashier",
          "pharmacy",
          "labratory",
          "imaging",
          "labratory_head",
          "imaging_head",
          "opd",
          "store",
          "reception",
          "hrm",
        ],
        route: "workPermission",
        icon: "workPermission",
      },
      {
        title: "Room",
        allowedRoles: ["admin"],
        route: "room",
        icon: "room",
      },
    ],
  },
  {
    title: "Reports",
    allowedRoles: [
      "admin",
      "nurse",
      "cashier",
      "pharmacy",
      "labratory",
      "imaging",
      "labratory_head",
      "imaging_head",
      "opd",
      "store",
      "reception",
      "hrm",
    ],
    route: "reports",
    icon: "reports",
  },
  {
    title: "Chat",
    allowedRoles: [
      "admin",
      "nurse",
      "cashier",
      "pharmacy",
      "labratory",
      "imaging",
      "labratory_head",
      "imaging_head",
      "opd",
      "store",
      "reception",
      "hrm",
    ],
    route: "chat",
    icon: "chat",
  },
  {
    title: "logintry",
    allowedRoles: ["admin"],
    route: "logintry",
    icon: "logintry",
  },
];
export { menusData };
