const path = {
  items: "/Items",
  nurse: "/nurse",
  register_patient: "/patient/register",
  patient: "/patient/patient_detail",
  update_patient: "/patient/update_patient",
  register_taff: "/user/register",
  staff: "/user/search_user",
  staff_update: "/user/update_user",
  staff_by_role: "/user/user_of_role",
  register_department: "/admin/register_department",
  department: "/admin/department_data",
  update_department: "/admin/update_department_data",
  inventory: "/store/inventory",
  inventory_detail: "/store/inventory_detail",
  item: "/store/inventory_item",
  update_item: "/store/inventory_item_detail",
  issue: "/store/issue",
  issue_confirm: "/store/issue_detail",
  issue_personal: "/store/user_issue_info",
  update_issue: "/store/issue_upadte",
  register_imaging: "/imaging/imaging_test_case",
  register_lab_group: "/lab/lab_test_group",
  register_lab_case: "/lab/lab_test_case",
  update_lab_test_case: "/lab/update_lab_test_case",
  get_lab_case_by_group: "/lab/lab_test_case_in_group",
  update_lab_group: "/lab/update_lab_test_group",
  lab_group: "/lab_group",
  lab_test_case: "/lab/lab_test_case",
  lab_test_case_by_gruop: "/lab/lab_test_case_in_group",
  patient_test_case: "/lab/lab_test_request",
  verification_test_case: "/lab/varify_outsource_lab_test",
  get_patient_test_case: "/lab/lab_test_history_data",
  all_lab_test_case_request: "/lab/lab_test_request",
  single_lab_test_case_request: "/lab/lab_test_history_data",
  updatae_lab_test_case_request: "/lab/enter_lab_test_history_detail",
  register_outsourced_test_case: "/lab/outsource_lab_test",
  measurement: "/common/measurement",
  measurement_pharmacy: "/pharmacy/medicine_unit_of_measurement",
  medicine_measurment_relation: "/pharmacy/unit_relation",
  medicine_measurment_list: "/pharmacy/units_of_medicine",

  medicine: "/pharmacy/medicine",
  medicine_detail: "/pharmacy/medicine_detail",
  medicine_category: "/pharmacy/medicine_category",
  dispensary_request: "/pharmacy/dispensary_request",
  dispensary_request_confirm: "/pharmacy/dispensary_request",
  pharmacy_neer_expire_instore: "/pharmacy/neer_expire_meds_instore",

  assing_patient_room: "/",

  medical_history_list: "/patient/medical_history",
  medical_history_patient_id: "/patient/read_medical_history_history",
  send_material_request: "/nurse/material_request",
  material_request_service_id: "/nurse/material_request_data",

  room: "/admin/room",
  update_room: "/admin/room_detail",
  get_staff_deprtment: "/user/user_in_department",
  room_staff: "/admin/room_member",
  get_room_staff: "/admin/room_member_detail",
  assing_patient_room_request: "/nurse/patient_service",
  nurse_patient_assigned: "/nurse/patient_service_request_nurse",
  update_nurse_patient_assigned: "/nurse/patient_service_update",

  patient_service_detail: "/nurse/patient_service_detail",

  vital_sign: "/nurse/vital_sign",
  update_vital_sign: "/nurse/vital_sign_update",
  patient_vital_sign: "/nurse/patient_vital_sign",
  patient_vital_sign_read: "/nurse/patient_vital_sign_read",

  make_appointment: "/common/appointment",
  update_appointment: "/common/update_appointment",
  single_make_appointment: "/common/read_user_appointment",

  reception_card_renewal: "/reception/write_card_renewal",
  cashier_payment_request: "/cashier/payment_request",
  card_renewal_payment: "/cashier/payment_approval",
  test_case_payment_done: "/cashier/payment_approval",
  single_prepayment_load: "/cashier/patient_prepayment_read",

  register_prepayment: "/cashier/patient_prepayment_write",

  annual_plan: "/common/annual_plan",
  annual_plan_unseen: "/common/read_unseen_annual_plan",
  annual_plan_make_read: "/common/mark_annual_plan_as_seen",
  annual_plan_persenal: "/common/read_user_annual_plan_history",

  prescription: "/pharmacy/prescription",
  prescription_unseen: "/pharmacy/read_waiting_prescription",
  prescription_persenal: "/pharmacy/prescription_info_with_service",
  prescription_payment: "/pharmacy/approve_prescription",

  surgical_order: "/nurse/surgical_order",
  surgical_orders_service: "/nurse/surgical_orders_service",
  surgical_order_data: "/nurse/surgical_order_data",

  insurance: "/insurance/insurance",
  insurance_single: "/insurance/insurance_data",
  insurance_member: "/insurance/insurance_members",
  insurance_member_options: "/insurance/update_insurance_member",

  reception_dashboard_card: "/reception/patient_data_with_all_state",
  reception_dashboard_linechart: "/reception/new_patients_in_this_year",
  cashier_dashboard_linechart: "/cashier/yearly_money_generated",

  piechart_lab_testcase_wise_dashboard: "/admin/lab_test_case_percentage",
  piechart_lab_vistor_wise_dashboard: "/admin/lab_percentage_per_visitor",
  general_info_dashboard: "/admin/general_informaton_in_date_range",
  nurse_done_dashboard: "/admin/nurse_user_general_info",
  opd_done_dashboard: "/admin/opd_user_general_info",
  cashier_done_dashboard: "/admin/cashier_general_info_for_one_user",
  pharmacy_done_dashboard: "/pharmacy/user_transactions_per_data_range",

  general_info_laboratory_head: "/lab/data_laboratory_for_head",

  assign_opd: "/nurse/send_to_opd",
  assigned_opd_list: "/nurse/",

  refferal: "/nurse/referal",
  read_refferal: "/nurse/read_referal",

  logout: "/user/logout",
  login: "/user/login",

  work_permission: "/common/work_permmision",
  work_permission_unseen: "/common/read_waiting_work_permmisions",
  work_permission_single: "/common/read_my_permmision_history",
  imaging_test_case: "/imaging_test",

  update_password: "/user/update_password",
};

export default path;
