const path = {
  items: "/Items",
  nurse: "/nurse",
  register_patient: "/patient/register",
  patient: "/patient/patient_detail",
  update_patient: "/patient/update_patient",
  register_taff: "/user/register",
  staff: "/user/search_user",
  register_department: "/admin/register_department",
  department: "/admin/department_data",
  update_department: "/admin/update_department_data",
  inventory: "/store/inventory",
  inventory_detail: "/store/inventory_detail",
  item: "/store/inventory_item",
  update_item: "/store/inventory_item_detail",
  issue: "/store/issue",
  update_issue: "/store/issue_upadte",
  register_imaging: "/imaging/imaging_test_case",
  register_lab_group: "/lab/lab_test_group",
  register_lab_case: "/lab/lab_test_case",
  get_lab_case_by_group: "/lab/lab_test_case_in_group",
  update_lab_group: "/lab/update_lab_test_group",
  lab_group: "/lab_group",
  lab_test_case: "/lab/lab_test_case",
  lab_test_case_by_gruop: "/lab/lab_test_case_in_group",
  update_lab_test_case: "/lab/update_lab_test_case",
  patient_test_case: "/lab/lab_test_request",
  get_patient_test_case: "/lab/lab_test_history_data",
  measurement: "/common/measurement",
  assing_patient_room: "/",

  room: "/admin/room",
  update_room: "/admin/room_detail",
  get_staff_deprtment: "/user/user_in_department",
  room_staff: "/admin/room_member",
  get_room_staff: "/admin/room_member_detail",
  assing_patient_room_request: "/nurse/patient_service",
  nurse_patient_assigned: "/nurse/patient_service_request_nurse",
  update_nurse_patient_assigned: "/nurse/patient_service_update",

  vital_sign: "/nurse/vital_sign",
  update_vital_sign: "/nurse/vital_sign_update",
  patient_vital_sign: "/nurse/patient_vital_sign",
  patient_vital_sign_read: "/nurse/patient_vital_sign_read",

  logout: "/user/logout",
  login: "/user/login",

  register_work_permission: "/register_work_permission",
  imaging_test_case: "/imaging_test",
  insurance: "/insurance",
};

export default path;
